const express = require("express");
const userRouter = express.Router();
const getUserController = require("../controllers/userController/getUserController");
const updateProfileController = require("../controllers/userController/updateProfileController");
const getCurrentUserController = require("../controllers/userController/getCurrentUserController");
const userAuth = require("../middlewares/userAuth");
userRouter.get("/users/:id", getUserController);
userRouter.put("/users/:id", updateProfileController);
userRouter.get("/me", userAuth, getCurrentUserController);
module.exports = userRouter;
